# Generated by Django 5.1.5 on 2025-01-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="docker_image",
            field=models.CharField(
                help_text="Enter the Docker image name (e.g., lacledeslan/gamesvr-hl2dm)",
                max_length=200,
                null=True,
            ),
        ),
    ]
