# Generated by Django 5.1.5 on 2025-01-19 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpanel", "0002_server_docker_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="description",
        ),
        migrations.AlterField(
            model_name="server",
            name="docker_image",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webpanel.game"
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="status",
            field=models.CharField(
                choices=[("online", "Online"), ("offline", "Offline")],
                default="offline",
                max_length=10,
            ),
        ),
    ]
