# Generated by Django 5.1.5 on 2025-01-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpanel", "0003_remove_game_description_alter_server_docker_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="name",
            field=models.CharField(default="hello world", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="server",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="port",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
