# Generated by Django 5.1.5 on 2025-01-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpanel", "0004_server_name_alter_server_ip_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="command_args",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="server",
            name="docker_run_command",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
