# Generated by Django 5.1.5 on 2025-02-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webpanel", "0005_server_command_args_server_docker_run_command"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="docker_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="server",
            old_name="docker_run_command",
            new_name="run_command",
        ),
    ]
