# Generated by Django 5.1.5 on 2025-02-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpanel", "0005_server_command_args_server_docker_run_command"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
