# Generated by Django 5.1.5 on 2025-02-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpanel", "0006_rename_docker_image_server_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="game_thumbnails/"
            ),
        ),
    ]
