# Generated by Django 5.1.5 on 2025-04-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpanel", "0007_game_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/game_thumbnails/"
            ),
        ),
    ]
