# Generated by Django 5.1.5 on 2025-04-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpanel", "0008_alter_game_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="container_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="server",
            name="last_log",
            field=models.TextField(blank=True, null=True),
        ),
    ]
