# Generated by Django 5.1.5 on 2025-04-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpanel", "0009_server_container_id_server_last_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="game_thumbnails/"
            ),
        ),
    ]
