# Generated by Django 5.1.5 on 2025-04-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpanel", "0010_alter_game_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="port",
            field=models.JSONField(default=dict),
        ),
    ]
