# Generated by Django 5.1.5 on 2025-04-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpanel", "0011_alter_server_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="port",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
