# Generated by Django 5.1.5 on 2025-04-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpanel", "0013_migrate_port_to_dict"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="query_protocol",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
