# Generated by Django 5.1.5 on 2025-04-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpanel", "0014_server_query_protocol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="query_protocol",
        ),
        migrations.AddField(
            model_name="game",
            name="query_protocol",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
